In [1]:
import requests
import json

In [2]:
lat = "42.098701"
lon = "-75.912537"
weather = requests.get(f"https://api.weather.gov/points/{lat},{lon}")

json_file = weather.json()
print(json.dumps(json_file,indent=3))

{
   "@context": [
      "https://geojson.org/geojson-ld/geojson-context.jsonld",
      {
         "@version": "1.1",
         "wx": "https://api.weather.gov/ontology#",
         "s": "https://schema.org/",
         "geo": "http://www.opengis.net/ont/geosparql#",
         "unit": "http://codes.wmo.int/common/unit/",
         "@vocab": "https://api.weather.gov/ontology#",
         "geometry": {
            "@id": "s:GeoCoordinates",
            "@type": "geo:wktLiteral"
         },
         "city": "s:addressLocality",
         "state": "s:addressRegion",
         "distance": {
            "@id": "s:Distance",
            "@type": "s:QuantitativeValue"
         },
         "bearing": {
            "@type": "s:QuantitativeValue"
         },
         "value": {
            "@id": "s:value"
         },
         "unitCode": {
            "@id": "s:unitCode",
            "@type": "@id"
         },
         "forecastOffice": {
            "@type": "@id"
         },
         "forecastGridData": {
            "@type": "@id"
         },
         "publicZone": {
            "@type": "@id"
         },
         "county": {
            "@type": "@id"
         }
      }
   ],
   "id": "https://api.weather.gov/points/42.0987,-75.9125",
   "type": "Feature",
   "geometry": {
      "type": "Point",
      "coordinates": [
         -75.9125,
         42.0987
      ]
   },
   "properties": {
      "@id": "https://api.weather.gov/points/42.0987,-75.9125",
      "@type": "wx:Point",
      "cwa": "BGM",
      "forecastOffice": "https://api.weather.gov/offices/BGM",
      "gridId": "BGM",
      "gridX": 66,
      "gridY": 57,
      "forecast": "https://api.weather.gov/gridpoints/BGM/66,57/forecast",
      "forecastHourly": "https://api.weather.gov/gridpoints/BGM/66,57/forecast/hourly",
      "forecastGridData": "https://api.weather.gov/gridpoints/BGM/66,57",
      "observationStations": "https://api.weather.gov/gridpoints/BGM/66,57/stations",
      "relativeLocation": {
         "type": "Feature",
         "geometry": {
            "type": "Point",
            "coordinates": [
               -75.909369,
               42.101331
            ]
         },
         "properties": {
            "city": "Binghamton",
            "state": "NY",
            "distance": {
               "unitCode": "wmoUnit:m",
               "value": 390.27849880895
            },
            "bearing": {
               "unitCode": "wmoUnit:degree_(angle)",
               "value": 221
            }
         }
      },
      "forecastZone": "https://api.weather.gov/zones/forecast/NYZ056",
      "county": "https://api.weather.gov/zones/county/NYC007",
      "fireWeatherZone": "https://api.weather.gov/zones/fire/NYZ210",
      "timeZone": "America/New_York",
      "radarStation": "KBGM"
   }
}

In [3]:
json_file.keys()

dict_keys(['@context', 'id', 'type', 'geometry', 'properties'])

In [4]:
api_key="1c6d9abd5e84aaba74a2b0718d16762bfde05797"
url = f"https://api.census.gov/data/2019/pep/charagegroups?get=NAME,POP&HISP=2&for=state:*&key={api_key}"

census_data = requests.get(url)
json_filejson = census_data.json()

json_filejson

[['NAME', 'POP', 'HISP', 'state'],
 ['Mississippi', '100110', '2', '28'],
 ['Missouri', '268708', '2', '29'],
 ['Montana', '43289', '2', '30'],
 ['Nebraska', '219645', '2', '31'],
 ['Nevada', '900600', '2', '32'],
 ['New Hampshire', '54589', '2', '33'],
 ['New Jersey', '1856844', '2', '34'],
 ['New Mexico', '1032942', '2', '35'],
 ['New York', '3751058', '2', '36'],
 ['North Carolina', '1025830', '2', '37'],
 ['North Dakota', '31532', '2', '38'],
 ['Ohio', '470462', '2', '39'],
 ['Oklahoma', '438110', '2', '40'],
 ['Oregon', '566847', '2', '41'],
 ['Pennsylvania', '1000150', '2', '42'],
 ['Rhode Island', '172644', '2', '44'],
 ['South Carolina', '307118', '2', '45'],
 ['South Dakota', '37351', '2', '46'],
 ['Tennessee', '391382', '2', '47'],
 ['Texas', '11525578', '2', '48'],
 ['Vermont', '12719', '2', '50'],
 ['Utah', '462051', '2', '49'],
 ['Virginia', '834422', '2', '51'],
 ['Washington', '991721', '2', '53'],
 ['West Virginia', '31162', '2', '54'],
 ['Wisconsin', '413208', '2', '55'],
 ['Wyoming', '58609', '2', '56'],
 ['Alabama', '223278', '2', '01'],
 ['Alaska', '53212', '2', '02'],
 ['Arizona', '2310590', '2', '04'],
 ['Arkansas', '236631', '2', '05'],
 ['California', '15574880', '2', '06'],
 ['Colorado', '1256904', '2', '08'],
 ['Delaware', '93391', '2', '10'],
 ['District of Columbia', '79477', '2', '11'],
 ['Connecticut', '600955', '2', '09'],
 ['Florida', '5663860', '2', '12'],
 ['Georgia', '1048724', '2', '13'],
 ['Idaho', '229490', '2', '16'],
 ['Hawaii', '150864', '2', '15'],
 ['Illinois', '2219882', '2', '17'],
 ['Indiana', '489353', '2', '18'],
 ['Iowa', '198550', '2', '19'],
 ['Kansas', '356073', '2', '20'],
 ['Kentucky', '174706', '2', '21'],
 ['Louisiana', '246972', '2', '22'],
 ['Maine', '23700', '2', '23'],
 ['Maryland', '643822', '2', '24'],
 ['Massachusetts', '854907', '2', '25'],
 ['Michigan', '528205', '2', '26'],
 ['Minnesota', '315130', '2', '27']]

In [10]:
import csv
import pandas as pd

In [11]:
json_filejson

[['NAME', 'POP', 'HISP', 'state'],
 ['Mississippi', '100110', '2', '28'],
 ['Missouri', '268708', '2', '29'],
 ['Montana', '43289', '2', '30'],
 ['Nebraska', '219645', '2', '31'],
 ['Nevada', '900600', '2', '32'],
 ['New Hampshire', '54589', '2', '33'],
 ['New Jersey', '1856844', '2', '34'],
 ['New Mexico', '1032942', '2', '35'],
 ['New York', '3751058', '2', '36'],
 ['North Carolina', '1025830', '2', '37'],
 ['North Dakota', '31532', '2', '38'],
 ['Ohio', '470462', '2', '39'],
 ['Oklahoma', '438110', '2', '40'],
 ['Oregon', '566847', '2', '41'],
 ['Pennsylvania', '1000150', '2', '42'],
 ['Rhode Island', '172644', '2', '44'],
 ['South Carolina', '307118', '2', '45'],
 ['South Dakota', '37351', '2', '46'],
 ['Tennessee', '391382', '2', '47'],
 ['Texas', '11525578', '2', '48'],
 ['Vermont', '12719', '2', '50'],
 ['Utah', '462051', '2', '49'],
 ['Virginia', '834422', '2', '51'],
 ['Washington', '991721', '2', '53'],
 ['West Virginia', '31162', '2', '54'],
 ['Wisconsin', '413208', '2', '55'],
 ['Wyoming', '58609', '2', '56'],
 ['Alabama', '223278', '2', '01'],
 ['Alaska', '53212', '2', '02'],
 ['Arizona', '2310590', '2', '04'],
 ['Arkansas', '236631', '2', '05'],
 ['California', '15574880', '2', '06'],
 ['Colorado', '1256904', '2', '08'],
 ['Delaware', '93391', '2', '10'],
 ['District of Columbia', '79477', '2', '11'],
 ['Connecticut', '600955', '2', '09'],
 ['Florida', '5663860', '2', '12'],
 ['Georgia', '1048724', '2', '13'],
 ['Idaho', '229490', '2', '16'],
 ['Hawaii', '150864', '2', '15'],
 ['Illinois', '2219882', '2', '17'],
 ['Indiana', '489353', '2', '18'],
 ['Iowa', '198550', '2', '19'],
 ['Kansas', '356073', '2', '20'],
 ['Kentucky', '174706', '2', '21'],
 ['Louisiana', '246972', '2', '22'],
 ['Maine', '23700', '2', '23'],
 ['Maryland', '643822', '2', '24'],
 ['Massachusetts', '854907', '2', '25'],
 ['Michigan', '528205', '2', '26'],
 ['Minnesota', '315130', '2', '27']]

In [12]:
csv_file = open("PopulationCensus.csv", "a", newline="", encoding="utf-8")
csv_writer = csv.writer(csv_file)
csv_writer.writerows(json_filejson)
csv_file.close()
sheet=pd.read_csv("PopulationCensus.csv")

In [13]:
sheet

                    NAME       POP  HISP  state
0            Mississippi    100110     2     28
1               Missouri    268708     2     29
2                Montana     43289     2     30
3               Nebraska    219645     2     31
4                 Nevada    900600     2     32
5          New Hampshire     54589     2     33
6             New Jersey   1856844     2     34
7             New Mexico   1032942     2     35
8               New York   3751058     2     36
9         North Carolina   1025830     2     37
10          North Dakota     31532     2     38
11                  Ohio    470462     2     39
12              Oklahoma    438110     2     40
13                Oregon    566847     2     41
14          Pennsylvania   1000150     2     42
15          Rhode Island    172644     2     44
16        South Carolina    307118     2     45
17          South Dakota     37351     2     46
18             Tennessee    391382     2     47
19                 Texas  11525578     2     48
20               Vermont     12719     2     50
21                  Utah    462051     2     49
22              Virginia    834422     2     51
23            Washington    991721     2     53
24         West Virginia     31162     2     54
25             Wisconsin    413208     2     55
26               Wyoming     58609     2     56
27               Alabama    223278     2      1
28                Alaska     53212     2      2
29               Arizona   2310590     2      4
30              Arkansas    236631     2      5
31            California  15574880     2      6
32              Colorado   1256904     2      8
33              Delaware     93391     2     10
34  District of Columbia     79477     2     11
35           Connecticut    600955     2      9
36               Florida   5663860     2     12
37               Georgia   1048724     2     13
38                 Idaho    229490     2     16
39                Hawaii    150864     2     15
40              Illinois   2219882     2     17
41               Indiana    489353     2     18
42                  Iowa    198550     2     19
43                Kansas    356073     2     20
44              Kentucky    174706     2     21
45             Louisiana    246972     2     22
46                 Maine     23700     2     23
47              Maryland    643822     2     24
48         Massachusetts    854907     2     25
49              Michigan    528205     2     26
50             Minnesota    315130     2     27

In [19]:
data_file = open("census_data.csv", "w", newline="", encoding="utf-8")
csv_writer = csv.writer(data_file)
csv_writer.writerow(["Name", "Pop", "HISP", "State"])


for list in json_filejson:
    if list == json_filejson[0]:
        pass
    else:
        name = list[0]
        pop = list[1]
        hisp = list[2]
        state = list[3]
        
        csv_writer.writerow([name, pop, hisp, state])


data_file.close()

In [22]:
sheet=pd.read_csv("census_data.csv")
sheet

                    Name       Pop  HISP  State
0            Mississippi    100110     2     28
1               Missouri    268708     2     29
2                Montana     43289     2     30
3               Nebraska    219645     2     31
4                 Nevada    900600     2     32
5          New Hampshire     54589     2     33
6             New Jersey   1856844     2     34
7             New Mexico   1032942     2     35
8               New York   3751058     2     36
9         North Carolina   1025830     2     37
10          North Dakota     31532     2     38
11                  Ohio    470462     2     39
12              Oklahoma    438110     2     40
13                Oregon    566847     2     41
14          Pennsylvania   1000150     2     42
15          Rhode Island    172644     2     44
16        South Carolina    307118     2     45
17          South Dakota     37351     2     46
18             Tennessee    391382     2     47
19                 Texas  11525578     2     48
20               Vermont     12719     2     50
21                  Utah    462051     2     49
22              Virginia    834422     2     51
23            Washington    991721     2     53
24         West Virginia     31162     2     54
25             Wisconsin    413208     2     55
26               Wyoming     58609     2     56
27               Alabama    223278     2      1
28                Alaska     53212     2      2
29               Arizona   2310590     2      4
30              Arkansas    236631     2      5
31            California  15574880     2      6
32              Colorado   1256904     2      8
33              Delaware     93391     2     10
34  District of Columbia     79477     2     11
35           Connecticut    600955     2      9
36               Florida   5663860     2     12
37               Georgia   1048724     2     13
38                 Idaho    229490     2     16
39                Hawaii    150864     2     15
40              Illinois   2219882     2     17
41               Indiana    489353     2     18
42                  Iowa    198550     2     19
43                Kansas    356073     2     20
44              Kentucky    174706     2     21
45             Louisiana    246972     2     22
46                 Maine     23700     2     23
47              Maryland    643822     2     24
48         Massachusetts    854907     2     25
49              Michigan    528205     2     26
50             Minnesota    315130     2     27